<?php

// autoload-classmap.php @generated by Mozart

$srcclasses = dirname(__FILE__);

return array(
   'SebastianBergmann\Diff\Diff' => $srcclasses . '/sebastian/diff/src/Diff.php',
   'SebastianBergmann\Diff\Parser' => $srcclasses . '/sebastian/diff/src/Parser.php',
   'SebastianBergmann\Diff\TimeEfficientLongestCommonSubsequenceCalculator' => $srcclasses . '/sebastian/diff/src/TimeEfficientLongestCommonSubsequenceCalculator.php',
   'SebastianBergmann\Diff\Output\DiffOnlyOutputBuilder' => $srcclasses . '/sebastian/diff/src/Output/DiffOnlyOutputBuilder.php',
   'SebastianBergmann\Diff\Output\DiffOutputBuilderInterface' => $srcclasses . '/sebastian/diff/src/Output/DiffOutputBuilderInterface.php',
   'SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder' => $srcclasses . '/sebastian/diff/src/Output/UnifiedDiffOutputBuilder.php',
   'SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder' => $srcclasses . '/sebastian/diff/src/Output/StrictUnifiedDiffOutputBuilder.php',
   'SebastianBergmann\Diff\Output\AbstractChunkOutputBuilder' => $srcclasses . '/sebastian/diff/src/Output/AbstractChunkOutputBuilder.php',
   'SebastianBergmann\Diff\LongestCommonSubsequenceCalculator' => $srcclasses . '/sebastian/diff/src/LongestCommonSubsequenceCalculator.php',
   'SebastianBergmann\Diff\Chunk' => $srcclasses . '/sebastian/diff/src/Chunk.php',
   'SebastianBergmann\Diff\Differ' => $srcclasses . '/sebastian/diff/src/Differ.php',
   'SebastianBergmann\Diff\Line' => $srcclasses . '/sebastian/diff/src/Line.php',
   'SebastianBergmann\Diff\ConfigurationException' => $srcclasses . '/sebastian/diff/src/Exception/ConfigurationException.php',
   'SebastianBergmann\Diff\InvalidArgumentException' => $srcclasses . '/sebastian/diff/src/Exception/InvalidArgumentException.php',
   'SebastianBergmann\Diff\Exception' => $srcclasses . '/sebastian/diff/src/Exception/Exception.php',
   'SebastianBergmann\Diff\MemoryEfficientLongestCommonSubsequenceCalculator' => $srcclasses . '/sebastian/diff/src/MemoryEfficientLongestCommonSubsequenceCalculator.php',
);